/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.4.0

Source Server         : WORKBASEPLUS
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : WORKBASEPLUS

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2020-12-02 12:52:41
*/


-- ----------------------------
-- Table structure for SYS_ADDRESS
-- ----------------------------
DROP TABLE SYS_ADDRESS;
CREATE TABLE SYS_ADDRESS (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  NULL ,
IS_USE NUMBER(10) DEFAULT 1 NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) NULL ,
CITY VARCHAR2(255 CHAR) NULL ,
CITY_NAME VARCHAR2(255 CHAR) NULL ,
COUNTY VARCHAR2(255 CHAR) NULL ,
COUNTY_NAME VARCHAR2(255 CHAR) NULL ,
PROVINCE VARCHAR2(255 CHAR) NULL ,
PROVINCE_NAME VARCHAR2(255 CHAR) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SYS_ADDRESS
-- ----------------------------

-- ----------------------------
-- Table structure for SYS_ORGANIZATION
-- ----------------------------
DROP TABLE SYS_ORGANIZATION;
CREATE TABLE SYS_ORGANIZATION (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
ADDRESS VARCHAR2(255 CHAR) NULL ,
ORGANIZATION_LVL NUMBER(10) NULL ,
ORGANIZATION_NAME VARCHAR2(255 CHAR) NULL ,
ORGANIZATION_NO VARCHAR2(100 CHAR) NULL ,
ORGANIZATION_TYPE VARCHAR2(50 BYTE) NULL ,
CITY VARCHAR2(50 CHAR) NULL ,
COUNTY VARCHAR2(50 CHAR) NULL ,
MAIL VARCHAR2(150 CHAR) NULL ,
PHONE VARCHAR2(50 CHAR) NULL ,
PROVINCE VARCHAR2(50 CHAR) NULL ,
SHORT_NAME VARCHAR2(255 CHAR) NULL ,
TAX VARCHAR2(50 CHAR) NULL ,
UP_ORGANIZATION_NO VARCHAR2(100 CHAR) NULL ,
UP_ID NUMBER(10) DEFAULT 0  NULL ,
UP_LVL0 VARCHAR2(100 CHAR) NULL ,
UP_LVL1 VARCHAR2(100 CHAR) NULL ,
UP_LVL2 VARCHAR2(100 CHAR) NULL ,
UP_LVL3 VARCHAR2(100 CHAR) NULL ,
UP_LVL4 VARCHAR2(100 CHAR) NULL ,
UP_LVL5 VARCHAR2(100 CHAR) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SYS_ORGANIZATION
-- ----------------------------
INSERT INTO SYS_ORGANIZATION VALUES ('1', TO_TIMESTAMP(' 2020-10-10 14:49:36:690000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-10 14:49:36:690000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', null, '0', '系统默认机构', 'SYS0', '1', null, null, null, null, null, '默认', null, null, '0', 'SYS0', null, null, null, null, null);

-- ----------------------------
-- Table structure for SYS_DICT
-- ----------------------------
DROP TABLE SYS_DICT;
CREATE TABLE SYS_DICT (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
DICT_NAME VARCHAR2(255 CHAR) NULL ,
DICT_NO VARCHAR2(100 CHAR) NULL ,
GROUP_NO VARCHAR2(100 BYTE) NULL ,
DICT_TYPE VARCHAR2(100 BYTE) NULL ,
GROUP_NAME VARCHAR2(255 BYTE) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;

INSERT INTO SYS_DICT VALUES ('1', TO_TIMESTAMP(' 2020-10-10 15:12:03:080000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-10 15:12:03:080000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1','0','1', null, '0', '类别1', '1', 'organization_type','1', '机构类别');
INSERT INTO SYS_DICT VALUES ('2', TO_TIMESTAMP(' 2020-10-10 15:12:03:087000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-10 15:12:03:087000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1','0','1', null, '0', '类别2', '2', 'organization_type','1', '机构类别');
INSERT INTO SYS_DICT VALUES ('6', TO_TIMESTAMP(' 2020-10-10 15:12:03:092000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-10 15:12:03:092000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1','0','1', null, '0', '类别3', '3', 'organization_type','1', '机构类别');
INSERT INTO SYS_DICT VALUES ('7', TO_TIMESTAMP(' 2020-10-12 10:29:14:482000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-12 10:29:14:482000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1','0','1', null, '0', '类别4', '4', 'organization_type','1', '机构类型');
INSERT INTO SYS_DICT VALUES ('8', TO_TIMESTAMP(' 2020-10-12 10:29:14:482000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-12 10:29:14:482000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1','0','1', null, '0', '', '', 'organization_type','0', '机构类型');

-- ----------------------------
-- Table structure for SYS_LOG
-- ----------------------------
DROP TABLE SYS_LOG;
CREATE TABLE SYS_LOG (
ID NUMBER(11) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 BYTE) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
MODE_TYPE VARCHAR2(255 BYTE) NULL ,
MODE_NAME VARCHAR2(255 BYTE) NULL ,
INFO VARCHAR2(4000 BYTE) NULL ,
OPER_USER VARCHAR2(100 BYTE) NULL ,
OPER_IP VARCHAR2(100 BYTE) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN SYS_LOG.OPER_USER IS '操作人';


-- ----------------------------
-- Table structure for SYS_ROLE
-- ----------------------------
DROP TABLE SYS_ROLE;
CREATE TABLE SYS_ROLE (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
ROLE_NAME VARCHAR2(255 CHAR) NULL ,
ROLE_NO VARCHAR2(100 CHAR) NULL ,
ROLE_TYPE VARCHAR2(100 CHAR) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN SYS_ROLE.IS_USE IS '是否启用 0停用1启用';

-- ----------------------------
-- Records of SYS_ROLE
-- ----------------------------
INSERT INTO SYS_ROLE VALUES ('1', TO_TIMESTAMP(' 2020-09-25 15:50:54:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-09-29 08:11:04:052000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', '系统最大权限角色', '0', '超级管理员', 'S0', '0');

-- ----------------------------
-- Table structure for SYS_ROLE_RIGHT
-- ----------------------------
DROP TABLE SYS_ROLE_RIGHT;
CREATE TABLE SYS_ROLE_RIGHT (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
HANDLE_TYPE VARCHAR2(100 CHAR) NULL ,
MENU_NO VARCHAR2(100 CHAR) NULL ,
ROLE_ID NUMBER(10) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SYS_ROLE_RIGHT
-- ----------------------------
INSERT INTO SYS_ROLE_RIGHT VALUES ('1', TO_TIMESTAMP(' 2020-10-13 15:19:00:915000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:915000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', '/welcome', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('2', TO_TIMESTAMP(' 2020-10-13 15:19:00:918000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:918000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', '/setting/account', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('3', TO_TIMESTAMP(' 2020-10-13 15:19:00:922000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:922000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', '/setting/dictionary', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('4', TO_TIMESTAMP(' 2020-10-13 15:19:00:924000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:924000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', '/setting/organization', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('5', TO_TIMESTAMP(' 2020-10-13 15:19:00:928000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:928000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', '/setting/log', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('6', TO_TIMESTAMP(' 2020-10-13 15:19:00:931000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:931000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', '/setting', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('7', TO_TIMESTAMP(' 2020-10-13 15:19:00:934000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:934000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/setting', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('8', TO_TIMESTAMP(' 2020-10-13 15:19:00:938000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:938000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/setting/role', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('9', TO_TIMESTAMP(' 2020-10-13 15:19:00:940000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:940000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/welcome', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('10', TO_TIMESTAMP(' 2020-10-13 15:19:00:943000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:943000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/setting/account', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('11', TO_TIMESTAMP(' 2020-10-13 15:19:00:945000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:945000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/setting/dictionary', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('13', TO_TIMESTAMP(' 2020-10-13 15:19:00:943000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:943000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/setting/organization', '1');
INSERT INTO SYS_ROLE_RIGHT VALUES ('14', TO_TIMESTAMP(' 2020-10-13 15:19:00:945000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-10-13 15:19:00:945000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '2', '/setting/log', '1');
-- ----------------------------
-- Table structure for SYS_USER
-- ----------------------------
DROP TABLE SYS_USER;
CREATE TABLE SYS_USER (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
ORGANIZATION_ID NUMBER(10) NULL ,
CARD VARCHAR2(50 CHAR) NULL ,
GENDER VARCHAR2(10 CHAR) NULL ,
LOGIN_DATE TIMESTAMP(6)  NULL ,
LOGIN_IP VARCHAR2(150 CHAR) NULL ,
LOGIN_MAC VARCHAR2(150 CHAR) NULL ,
LOGIN_NAME VARCHAR2(100 CHAR) NULL ,
LOGIN_PASS VARCHAR2(100 CHAR) NULL ,
MAIL VARCHAR2(50 CHAR) NULL ,
NICK_NAME VARCHAR2(255 CHAR) NULL ,
PHONE VARCHAR2(50 CHAR) NULL ,
TAX VARCHAR2(50 CHAR) NULL ,
USER_NAME VARCHAR2(255 CHAR) NULL ,
USER_TYPE VARCHAR2(100 BYTE) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SYS_USER
-- ----------------------------
INSERT INTO SYS_USER VALUES ('1', TO_TIMESTAMP(' 2020-09-25 15:34:07:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-09-29 08:11:25:207000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', '1', null, null, TO_TIMESTAMP(' 2020-10-13 16:52:10:069000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '10.101.70.42', null, 'admin', 'uG4EHlo57M4=', null, null, null, null, '管理员', '0');

-- ----------------------------
-- Table structure for SYS_USER_ROLE
-- ----------------------------
DROP TABLE SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE (
ID NUMBER(10) NOT NULL ,
DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
IS_USE NUMBER(10) DEFAULT 1  NULL ,
IS_DEL NUMBER(10) DEFAULT 0 NULL ,
VERSION NUMBER(10) NULL ,
REMARK VARCHAR2(255 CHAR) NULL ,
SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
LOGIN_NAME VARCHAR2(100 CHAR) NULL ,
ROLE_ID NUMBER(10) NULL ,
USER_TYPE NUMBER(10) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SYS_USER_ROLE
-- ----------------------------
INSERT INTO SYS_USER_ROLE VALUES ('1', TO_TIMESTAMP(' 2020-09-25 15:39:59:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), TO_TIMESTAMP(' 2020-09-25 15:40:02:000000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '1', '0', '1', null, '0', 'admin', '1', '0');

-- ----------------------------
-- Sequence structure for SEQ_SYS_ADDRESS
-- ----------------------------
DROP SEQUENCE SEQ_SYS_ADDRESS;
CREATE SEQUENCE SEQ_SYS_ADDRESS
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_ORGANIZATION
-- ----------------------------
DROP SEQUENCE SEQ_SYS_ORGANIZATION;
CREATE SEQUENCE SEQ_SYS_ORGANIZATION
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_DICT
-- ----------------------------
DROP SEQUENCE SEQ_SYS_DICT;
CREATE SEQUENCE SEQ_SYS_DICT
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_DICT_TYPE
-- ----------------------------
DROP SEQUENCE SEQ_SYS_DICT_TYPE;
CREATE SEQUENCE SEQ_SYS_DICT_TYPE
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_LOG
-- ----------------------------
DROP SEQUENCE SEQ_SYS_LOG;
CREATE SEQUENCE SEQ_SYS_LOG
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999999999999999999999999
 START WITH 28
 NOCACHE ;

-- ----------------------------
-- Sequence structure for SEQ_SYS_ROLE
-- ----------------------------
DROP SEQUENCE SEQ_SYS_ROLE;
CREATE SEQUENCE SEQ_SYS_ROLE
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 61
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_ROLE_RIGHT
-- ----------------------------
DROP SEQUENCE SEQ_SYS_ROLE_RIGHT;
CREATE SEQUENCE SEQ_SYS_ROLE_RIGHT
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 441
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_USER
-- ----------------------------
DROP SEQUENCE SEQ_SYS_USER;
CREATE SEQUENCE SEQ_SYS_USER
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_SYS_USER_ROLE
-- ----------------------------
DROP SEQUENCE SEQ_SYS_USER_ROLE;
CREATE SEQUENCE SEQ_SYS_USER_ROLE
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Indexes structure for table SYS_ADDRESS
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ADDRESS
-- ----------------------------
ALTER TABLE SYS_ADDRESS ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_ADDRESS ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ADDRESS
-- ----------------------------
ALTER TABLE SYS_ADDRESS ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_ORGANIZATION
-- ----------------------------

-- ----------------------------
-- Uniques structure for table SYS_ORGANIZATION
-- ----------------------------
ALTER TABLE SYS_ORGANIZATION ADD UNIQUE (ORGANIZATION_NO);

-- ----------------------------
-- Checks structure for table SYS_ORGANIZATION
-- ----------------------------
ALTER TABLE SYS_ORGANIZATION ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_ORGANIZATION ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ORGANIZATION
-- ----------------------------
ALTER TABLE SYS_ORGANIZATION ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_DICT
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_DICT
-- ----------------------------
ALTER TABLE SYS_DICT ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_DICT ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_DICT
-- ----------------------------
ALTER TABLE SYS_DICT ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_LOG
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_LOG
-- ----------------------------
ALTER TABLE SYS_LOG ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_LOG
-- ----------------------------
ALTER TABLE SYS_LOG ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_ROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ROLE
-- ----------------------------
ALTER TABLE SYS_ROLE ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_ROLE ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ROLE
-- ----------------------------
ALTER TABLE SYS_ROLE ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_ROLE_RIGHT
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_ROLE_RIGHT
-- ----------------------------
ALTER TABLE SYS_ROLE_RIGHT ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_ROLE_RIGHT ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_ROLE_RIGHT
-- ----------------------------
ALTER TABLE SYS_ROLE_RIGHT ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_USER
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_USER
-- ----------------------------
ALTER TABLE SYS_USER ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_USER ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_USER
-- ----------------------------
ALTER TABLE SYS_USER ADD PRIMARY KEY (ID);

-- ----------------------------
-- Indexes structure for table SYS_USER_ROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_USER_ROLE
-- ----------------------------
ALTER TABLE SYS_USER_ROLE ADD CHECK (ID IS NOT NULL);
ALTER TABLE SYS_USER_ROLE ADD CHECK (ID IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_USER_ROLE
-- ----------------------------
ALTER TABLE SYS_USER_ROLE ADD PRIMARY KEY (ID);


CREATE TABLE RULES_MAIN (
    ID NUMBER(10) NOT NULL PRIMARY key,
    DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
    DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
    IS_USE NUMBER(10) DEFAULT 1  NULL ,
    IS_DEL NUMBER(10) DEFAULT 0 NULL ,
    VERSION NUMBER(10) NULL ,
    REMARK VARCHAR2(255 CHAR) NULL ,
    SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
    IN_CODE VARCHAR2(100 CHAR) NULL , -- 内部编码用于作为唯一标识连接
    CODE VARCHAR2(100 CHAR) NULL , -- 唯一编码
    TITLE VARCHAR2(255 CHAR) NULL , -- 标题
    SUB_TITLE VARCHAR2(255 CHAR) NULL , -- 副标题
    TAGS VARCHAR2(255 CHAR) NULL , -- 标签
    KEY_WORDS VARCHAR2(255 CHAR) NULL , -- 关键词
    ORGANIZATION_ID NUMBER(10) NULL ,-- 所属机构ID
    SCOPE VARCHAR2(255 CHAR) NULL , -- 规范范围
    REASON VARCHAR2(255 CHAR) NULL , -- 原因
    BASIS VARCHAR2(255 CHAR) NULL , -- 制度依据
    IS_KEY NUMBER(3) NULL , -- 是否是关键制度
    TYPE NUMBER(3) NULL , -- 类型 0集团级别 1公司级别 2基层级别
    SERVICE_TYPE VARCHAR2(10 CHAR) NULL , -- 分类
    CLASS_TYPE VARCHAR2(10 CHAR) NULL , -- 分类
    YEAR_TYPE VARCHAR2(10 CHAR) NULL , -- 分类
    IN_TYPE VARCHAR2(10 CHAR) NULL , -- 分类
    LVL NUMBER(10) NULL , -- 制度等级
    SPONSOR VARCHAR2(100 CHAR) NULL ,-- 起草者
    FROM_TYPE NUMBER(3) NULL , -- 来源类别 0 本地发起 1 公文传输
    FLOW_NODE NUMBER(5) NULL ,-- 审批节点
    FLOW_STATUS NUMBER(5) NULL ,-- 审批状态
    MODIFY_USER VARCHAR2(100 CHAR) NULL , -- 最后修改人
    CONFIRM_USER VARCHAR2(100 CHAR) NULL , -- 确认人
    RELATION_USER VARCHAR2(100 CHAR) NULL , -- 关联人
    STATUS NUMBER(3) NULL ,-- 状态 0现行 1试行/暂行 2审批中  3废止
    RELATION_STATUS NUMBER(3) NULL ,-- 状态 0不需要承接，1待承接 2已承接
    CONFIRM_STATUS NUMBER(3) NULL -- 状态 0未分类 1是规章制度 2不是规章制度

)
    LOGGING
    NOCOMPRESS
    NOCACHE
;

CREATE SEQUENCE SEQ_RULES_MAIN
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    START WITH 21
    CACHE 20;

CREATE TABLE RULES_RELATION (
    ID NUMBER(10) NOT NULL PRIMARY key,
    DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
    DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
    IS_USE NUMBER(10) DEFAULT 1  NULL ,
    IS_DEL NUMBER(10) DEFAULT 0 NULL ,
    VERSION NUMBER(10) NULL ,
    REMARK VARCHAR2(255 CHAR) NULL ,
    SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
    IN_CODE VARCHAR2(100 CHAR) NULL , -- 内部编码用于作为唯一标识连接
    TYPE NUMBER(3) NULL , -- 类型 0承接 1替代 2关联
    RELATION_STATUS NUMBER(3) NULL ,-- 状态 0不需要承接，1待承接 2已承接
    RELATION_LVL NUMBER(3) NULL ,-- 状态 0被承接制度 1承接制度
    UP_IN_CODE VARCHAR2(100 CHAR) NULL -- 父级编码

)
    LOGGING
    NOCOMPRESS
    NOCACHE
;

CREATE SEQUENCE SEQ_RULES_RELATION
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    START WITH 21
    CACHE 20;

CREATE TABLE RULES_HISTORY (
   ID NUMBER(10) NOT NULL PRIMARY key,
   DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
   DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
   IS_USE NUMBER(10) DEFAULT 1  NULL ,
   IS_DEL NUMBER(10) DEFAULT 0 NULL ,
   VERSION NUMBER(10) NULL ,
   REMARK VARCHAR2(255 CHAR) NULL ,
   SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
   IN_CODE VARCHAR2(100 CHAR) NULL , -- 内部编码用于作为唯一标识连接
   HANDLE_TYPE NUMBER(3) NULL , -- 类型 0承接 1替代 2关联
   HANDLE_DESCRIBE VARCHAR2(255 CHAR) NULL ,-- 状态 0不需要承接，1待承接 2已承接
   UP_IN_CODE VARCHAR2(100 CHAR) NULL -- 父级编码

)
    LOGGING
    NOCOMPRESS
    NOCACHE
;

CREATE SEQUENCE SEQ_RULES_HISTORY
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    START WITH 21
    CACHE 20;



CREATE TABLE RULES_FILE (
    ID NUMBER(10) NOT NULL PRIMARY key,
    DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
    DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
    IS_USE NUMBER(10) DEFAULT 1  NULL ,
    IS_DEL NUMBER(10) DEFAULT 0 NULL ,
    VERSION NUMBER(10) NULL ,
    REMARK VARCHAR2(255 CHAR) NULL ,
    SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
    IN_CODE VARCHAR2(100 CHAR) NULL , -- 内部编码用于作为唯一标识连接
    SERVICE_TYPE NUMBER(3) NULL , -- 类型 0制度文件
    FILE_TYPE NUMBER(3) NULL , -- 类型 0文件 1图片
    FILE_NAME VARCHAR2(255 CHAR) NULL ,-- 文件名称
    FILE_PATH VARCHAR2(255 CHAR) NULL ,-- 状态 0不需要承接，1待承接 2已承接
    FILE_ALL_PATH VARCHAR2(255 CHAR) NULL -- 状态 0不需要承接，1待承接 2已承接

)
    LOGGING
    NOCOMPRESS
    NOCACHE
;

CREATE SEQUENCE SEQ_RULES_FILE
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    START WITH 21
    CACHE 20;



CREATE TABLE FLOW_TASK (
   ID NUMBER(10) NOT NULL PRIMARY key,
   DT_CREA_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
   DT_UPDATE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
   DT_DONE_DATE_TIME TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NULL ,
   IS_USE NUMBER(10) DEFAULT 1  NULL ,
   IS_DEL NUMBER(10) DEFAULT 0 NULL ,
   VERSION NUMBER(10) NULL ,
   REMARK VARCHAR2(255 CHAR) NULL ,
   SHOW_ORDER NUMBER(10) DEFAULT 0  NULL ,
   IN_CODE VARCHAR2(100 CHAR) NULL , -- 内部编码用于作为唯一标识连接
   TITLE VARCHAR2(100 CHAR) NULL ,-- 任务内容
   CONTENT VARCHAR2(255 CHAR) NULL ,-- 任务内容
   TASK_TYPE NUMBER(3) NULL , -- 类型 0需处理 1通知
   HANDLER VARCHAR2(100 CHAR) NULL ,-- 待处理人
   GIVER VARCHAR2(100 CHAR) NULL ,-- 待处理人
   REASON VARCHAR2(255 CHAR) NULL ,-- 处理结果原因
   RESULT NUMBER(5) NULL , -- 类型 0同意 1驳回
   STATUS NUMBER(5) NULL , -- 类型 0未处理 1已处理 -1取消
   NODE VARCHAR2(255 CHAR) NULL -- 流程节点

)
    LOGGING
    NOCOMPRESS
    NOCACHE
;

CREATE SEQUENCE SEQ_FLOW_TASK
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    START WITH 21
    CACHE 20;
